from collections.abc import Sequence

from race_engineer.voice.intent.models import VoiceIntent

IntentRule = tuple[VoiceIntent, Sequence[str]]

# First matching rule wins. More specific intents are listed first.
INTENT_RULES: tuple[IntentRule, ...] = (
    (
        VoiceIntent.GAP,
        (
            "gap ahead",
            "gap behind",
            "gap to the car ahead",
            "gap to the car behind",
            "gap to car ahead",
            "gap to car behind",
            "interval ahead",
            "interval behind",
            "time gap",
            "track gap",
            "delta ahead",
            "delta behind",
            "car ahead gap",
            "car behind gap",
            "seconds ahead",
            "seconds behind",
            "how far ahead",
            "how far behind",
            "gap to leader",
            "gap to p1",
            "interval to leader",
            "gap",
            "interval",
            "delta",
        ),
    ),
    (
        VoiceIntent.FUEL,
        (
            "fuel remaining",
            "fuel left",
            "fuel level",
            "fuel usage",
            "fuel consumption",
            "fuel per lap",
            "fuel save",
            "fuel saving",
            "enough fuel",
            "need fuel",
            "pit for fuel",
            "make it on fuel",
            "run out of fuel",
            "tank level",
            "gas left",
            "gas remaining",
            "petrol",
            "gallons",
            "liters",
            "litres",
            "fuel",
            "gas",
            "tank",
        ),
    ),
    (
        VoiceIntent.LAP,
        (
            "last lap time",
            "best lap time",
            "current lap time",
            "lap time",
            "lap times",
            "last lap",
            "best lap",
            "current lap",
            "previous lap",
            "that lap",
            "sector time",
            "sector times",
            "sector 1",
            "sector 2",
            "sector 3",
            "sector one",
            "sector two",
            "sector three",
            "personal best",
            "purple sector",
            "lap delta",
            "what lap",
            "which lap",
            "sectors",
        ),
    ),
    (
        VoiceIntent.POSITION,
        (
            "what position",
            "my position",
            "class position",
            "overall position",
            "overall standing",
            "race position",
            "track position",
            "where am i running",
            "where am i",
            "what place",
            "my place",
            "my standing",
            "in the standings",
            "on the lead lap",
            "positions",
            "standing",
            "standings",
            "position",
            "place",
        ),
    ),
    (
        VoiceIntent.COACHING,
        (
            "racing line",
            "brake point",
            "brake points",
            "trail brake",
            "trail braking",
            "turn in",
            "apex",
            "coach me",
            "coaching",
            "coach",
            "advice",
            "help me improve",
            "help me go faster",
            "go faster",
            "drive faster",
            "technique",
            "tip",
            "tips",
            "improve",
            "faster lap",
            "slower lap",
            "pace",
            "braking",
            "brake later",
            "brake earlier",
        ),
    ),
)
